name = "Contributor"
license = "MIT"
licenselink = "https://github.com/leemaret/contributor/blob/master/LICENSE"
description = "A Hugo theme using Primer.css with an emphasis on contribution history."
homepage = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Lee Maret"
  homepage = "https://github.com/leemaret"
